# Generated by Django 4.2.6 on 2023-10-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideas1', models.CharField(blank=True, max_length=255, null=True)),
                ('ideas2', models.CharField(blank=True, max_length=255, null=True)),
                ('ideas3', models.CharField(blank=True, max_length=255, null=True)),
                ('ideas4', models.CharField(blank=True, max_length=255, null=True)),
                ('ideas5', models.CharField(blank=True, max_length=255, null=True)),
                ('interview', models.TextField(blank=True, null=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='act2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ODSideas1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ODSideas2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ODSideas3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ODSideas4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ODSideas5', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consequences1', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences2', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences3', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences4', models.CharField(blank=True, max_length=255, null=True)),
                ('consequences5', models.CharField(blank=True, max_length=255, null=True)),
                ('problem', models.CharField(blank=True, max_length=255, null=True)),
                ('causes1', models.CharField(blank=True, max_length=255, null=True)),
                ('causes2', models.CharField(blank=True, max_length=255, null=True)),
                ('causes3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='act3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='act4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='actFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='actInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('password_confirmation', models.CharField(max_length=128)),
                ('isSuperAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('progress', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=15)),
                ('appRating', models.PositiveSmallIntegerField(blank=True, default=3, null=True)),
                ('currentActivity', models.PositiveSmallIntegerField(default=0)),
                ('act1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.act1')),
                ('act2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.act2')),
                ('act3ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.act3')),
                ('act4ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.act4')),
                ('actFinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.actfinal')),
                ('actInit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SEL4C.actinicial')),
            ],
        ),
    ]
