# Generated by Django 4.2.6 on 2023-10-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='discipline',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
