# Generated by Django 4.2.6 on 2023-10-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0003_remove_act4_retro_remove_actfinal_pitch_act4_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actinicial',
            old_name='name',
            new_name='listOfAnswers',
        ),
    ]
