# Generated by Django 4.2.6 on 2023-10-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0005_remove_manager_issuperadmin_manager_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password_confirmation',
        ),
    ]
