# Generated by Django 4.2.6 on 2023-10-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4C', '0006_remove_manager_password_confirmation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actInicial',
            new_name='actInitial',
        ),
    ]
